name: SpreadsheetにPull Requestの情報を送信
on:
  pull_request:
    types:
      - closed
jobs:
  metrix-info:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: post github info
        run: |
          gh api graphql -f id="${{ github.event.pull_request.node_id }}" -f query='
            query ($id: ID!) {
              node(id: $id) {
                ... on PullRequest {
                  repository {
                    name
                  }
                  title
                  author {
                    login
                  }
                  url
                  baseRefName
                  headRefName
                  commits(first: 1) {
                    nodes {
                      commit {
                        authoredDate
                      }
                    }
                  }
                  createdAt
                  mergedAt
                  additions
                  deletions
                  reviews(first: 1) {
                    nodes {
                      ... on PullRequestReview {
                        createdAt
                      }
                    }
                  }
                }
              }
            }
          ' |
          # tokenで認証を行なっている
          jq -r '.data.node |
            {
              data: {
                repository: .repository.name,
                title: .title,
                user: .author.login,
                url: .url,
                base: .baseRefName,
                head: .headRefName,
                firstCommittedAt: .commits.nodes[0].commit.authoredDate,
                createdAt: .createdAt,
                firstReviewedAt: .reviews.nodes[0].createdAt,
                mergedAt: .mergedAt,
                additions: .additions,
                deletions: .deletions
              },
              type: "lead_time"
            } |
            @json' |
          curl -L -H "Content-Type: application/json" -d @- "https://script.google.com/a/macros/geniee.co.jp/s/AKfycbzvB8y42Myas2ybReAdYx4Z8SonlImAIcpgKiCJ-mzzGJYbueDF4c2pcVd12Zog3HH8Ww/exec"
